@startuml
class QuizAstralBody {
    + isMassPublic : bool
    + isVelocityPublic : bool
    + isAngularVelocityPublic : bool
    + isGravityPublic : bool
    + isSizePublic : bool
    + globalAngularVelocity : float
    + _period : float
    + isPeriodPublic : bool
    + _radius : float
    + isRadiusPublic : bool
    + _anglePerT : float
    + isAnglePerTPublic : bool
    + _distancePerT : float
    + isDistancePerTPublic : bool
    + _t : float
    + isTPublic : bool
    + period : float <<get>> <<set>>
    + radius : float <<get>> <<set>>
    + anglePerT : float <<get>> <<set>>
    + distancePerT : float <<get>> <<set>>
    + t : float <<get>> <<set>>
    + oriRadius : float <<get>> <<set>>
    + UpdateQuizAstralBody() : void
    + UpdateHighCost() : void
    + UpdateLowCost() : void
    + UpdateQuizAstralBodyPer() : void
    + GetQuizConditionString() : string
    + CheckPublicity() : bool
}
AstralBody <|-- QuizAstralBody
@enduml
