@startuml
class CameraLayerMixer {
    + enableLayer0 : bool
    + enableLayer1 : bool
    + GetRenderResult() : RenderTexture
}
CustomPostProcessingBase <|-- CameraLayerMixer
CameraLayerMixer --> "cameraMixer" CameraMixer
CameraLayerMixer --> "layerCamera" LayerCamera
CameraLayerMixer --> "mixShader" Shader
CameraLayerMixer --> "_mixMaterial" Material
CameraLayerMixer --> "_renderResultRT" RenderTexture
CameraLayerMixer --> "MixMaterial" Material
@enduml
