@startuml
class PhysicBase <<static>> {
    + {static} G : float = 6.67f
    + {static} GetG() : float
    + {static} GetRealG() : double
}
interface IOrbitCalculator {
    CalculateOrbit(t:int, totalNumber:int) : Vector3
    DrawOrbit(lineRenderer:LineRenderer, totalNumber:int) : void
    GenerateOrbit() : void
}
class "List`1"<T> {
}
IOrbitCalculator --> "OrbitPoints<Vector3>" "List`1"
@enduml
