@startuml
class QuizStarsGroupUI {
    + _starCount : int
    + starCount : int <<get>> <<set>>
    + CalculateSuccessStars() : void
    + ShowStars() : void
}
class "List`1"<T> {
}
MonoBehaviour <|-- QuizStarsGroupUI
QuizStarsGroupUI o-> "quizStarUis<QuizStarUI>" "List`1"
QuizStarsGroupUI --> "globalTimer" GlobalTimer
@enduml
