@startuml
class QuizEditorUI {
    + SaveQuiz() : void
    + ReloadScene() : void
    + ChangeQuizType(type:int) : void
    + SettingToProp() : void
    + MainToSetting() : void
    + SettingToMain() : void
    + ToTestMode() : void
}
MonoBehaviour <|-- QuizEditorUI
QuizEditorUI --> "mainPanel" GameObject
QuizEditorUI --> "quizSetting" GameObject
QuizEditorUI --> "prop" GameObject
QuizEditorUI --> "nameField" InputField
@enduml
