@startuml
class AstralBodyEditorUI {
    + isEnableEdit : bool = true
    + isEnableEditorPanel : bool = true
    + <<virtual>> OnAstralBodySet() : void
    + EditVelocity() : void
    + OpenConicSectionPanel() : void
    + CloseConicSectionPanel() : void
    + <<virtual>> SetVelocityInCircle() : void
    + ClosePanel() : void
    + MainToStyleSheet() : void
    + StyleSheetToMain() : void
}
class "List`1"<T> {
}
MonoBehaviour <|-- AstralBodyEditorUI
AstralBodyEditorUI --> "gravityTracing" GravityTracing
AstralBodyEditorUI --> "positionEditorUI" PositionEditorUI
AstralBodyEditorUI --> "velocityEditorUI" VelocityEditorUI
AstralBodyEditorUI --> "normalPanel" GameObject
AstralBodyEditorUI --> "forceUI" VectorUI
AstralBodyEditorUI --> "velocityUI" VectorUI
AstralBodyEditorUI --> "lengthUIList<LengthUI>" "List`1"
AstralBodyEditorUI --> "orbitPanelUI" OrbitPanelUI
AstralBodyEditorUI --> "editorPanel" GameObject
AstralBodyEditorUI --> "varLineUis<VarLineUI>" "List`1"
AstralBodyEditorUI --> "mainPanel" GameObject
AstralBodyEditorUI --> "styleSheetPanel" StarStyleSettingUI
AstralBodyEditorUI --> "astralBody" AstralBody
@enduml
