@startuml
class LengthUI {
    + ShowLength() : void
}
MonoBehaviour <|-- LengthUI
LengthUI --> "lengthSpline" SplineComputer
LengthUI --> "lengthCalculator" LengthCalculator
LengthUI --> "lengthText" Text
LengthUI --> "astralBody" AstralBody
LengthUI --> "targetAstralBody" AstralBody
@enduml
