@startuml
class SelectorUI {
    + _isLocked : bool
    + isLocked : bool <<get>> <<set>>
    + Update() : void
    + FocusOn() : void
    + CancelFocus() : void
}
MonoBehaviour <|-- SelectorUI
SelectorUI --> "outlineCatcher" OutlineCatcher
SelectorUI --> "astralBodyEditorUI" AstralBodyEditorUI
SelectorUI --> "selectedGameObject" GameObject
@enduml
