@startuml
class TutorialUI {
    + tutorialName : string
    + curStep : int <<get>> <<set>>
    + StartTutorial() : void
    + GetTutorialCLipsList() : void
    + GenerateTutorialName() : void
    + NextStep() : void
    + FormerStep() : void
    + Quit() : void
}
class "List`1"<T> {
}
MonoBehaviour <|-- TutorialUI
TutorialUI --> "awakePanel" GameObject
TutorialUI --> "tutorialClips<GameObject>" "List`1"
TutorialUI --> "tutorialManagerUI" TutorialManagerUI
@enduml
