@startuml
class VoiceGenerator {
    + content : string <<get>> <<set>>
    + SpeakContent() : void
    + Speak() : void
    + Speak(content:string) : void
    + OnAudioLoadAndPaly(url:string, type:AudioType, audio:AudioSource) : IEnumerator
}
class WAVE_Header <<struct>> {
    + RIFF_ID : int
    + File_Size : int
    + RIFF_Type : int
    + FMT_ID : int
    + FMT_Size : int
    + FMT_Tag : short
    + FMT_Channel : ushort
    + FMT_SamplesPerSec : int
    + AvgBytesPerSec : int
    + BlockAlign : ushort
    + BitsPerSample : ushort
    + DATA_ID : int
    + DATA_Size : int
}
MonoBehaviour <|-- VoiceGenerator
VoiceGenerator +-- WAVE_Header
@enduml
