@startuml
class CameraMixer {
    + GetRenderResult() : RenderTexture
}
CustomPostProcessingBase <|-- CameraMixer
CameraMixer --> "renderTexOuter" OutlineCatcher
CameraMixer --> "renderTexture" RenderTexture
CameraMixer --> "mixShader" Shader
CameraMixer o-> "edgeColor" Color
CameraMixer --> "_mixMaterial" Material
CameraMixer --> "_renderResultRT" RenderTexture
CameraMixer --> "MixMaterial" Material
@enduml
