@startuml
interface IRenderTexOuter {
    GetRenderResult() : RenderTexture
}
class CustomPostProcessingBase {
}
MonoBehaviour <|-- CustomPostProcessingBase
CustomPostProcessingBase --> "mainCamera" Camera
@enduml
