@startuml
class OutlineCatcher {
    + edgeOnly : float = 1f
    + edgeSize : float = 0.5f
    + GetRenderResult() : RenderTexture
    + AddTarget(target:GameObject) : void
    + RemoveTarget(target:GameObject) : void
    + SetOutline() : void
}
CustomPostProcessingBase <|-- OutlineCatcher
IRenderTexOuter <|-- OutlineCatcher
OutlineCatcher --> "outlineCamera" Camera
OutlineCatcher --> "outlineShader" Shader
OutlineCatcher o-> "edgeColor" Color
OutlineCatcher o-> "backgroundColor" Color
OutlineCatcher --> "OutlineMaterial" Material
@enduml
